import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { expect } from '@playwright/test';
import { agentFixture } from './fixtures/agent-fixture.mjs';

test('AgentUI saves versioned Hive and host instructions, applies them locally and preserves local conflicts', { timeout: 120000 }, async t => {
  const f = await agentFixture(t, { width: 1280, height: 1000 }, false, '0.154.0', true);
  const target = join(f.config.settings.nativeHome, 'AGENTS.override.md');
  await writeFile(join(f.config.settings.nativeHome, 'AGENTS.md'), 'Local baseline');
  await f.open();
  await f.page.getByRole('link', { name: 'Settings', exact: true }).click();
  await f.page.getByRole('link', { name: 'Hive settings', exact: true }).click();
  const global = f.page.getByRole('region', { name: 'Hive instructions', exact: true });
  await expect(global.getByText('Packaged default template', { exact: true })).toBeVisible();
  const hiveOverride = global.getByRole('switch', { name: 'Override packaged defaults', exact: true });
  await expect(hiveOverride).not.toBeChecked();
  await hiveOverride.click();
  await global.getByLabel('Hive AGENTS.md').fill('Hive-wide preference');
  await global.getByRole('button', { name: 'Save instructions', exact: true }).click();
  await expect(global.getByRole('status')).toContainText('Saved revision 1');
  await expect(global.getByText('Hive AGENTS.md override', { exact: true })).toBeVisible();
  await expect.poll(() => readFile(target, 'utf8').catch(() => ''), { timeout: 20000 }).toContain('Hive-wide preference');
  const saved = await f.client.request('objects.stat', { path: '/ivy-agent-instructions' });
  assert.equal(saved.currentRevision, 1);
  await f.page.goto(f.url + '#/host-settings?node=browser-agent');
  const host = f.page.getByRole('region', { name: 'Host instructions', exact: true });
  await host.getByRole('switch', { name: 'Use host-specific instructions', exact: true }).click();
  await host.getByLabel('Host instruction text').fill('Host-specific preference');
  await host.getByRole('button', { name: 'Save instructions', exact: true }).click();
  await expect.poll(() => readFile(target, 'utf8'), { timeout: 20000 }).toContain('Host-specific preference');
  const content = await readFile(target, 'utf8');
  assert.ok(content.indexOf('Local baseline') < content.indexOf('Hive-wide preference'));
  assert.ok(content.indexOf('Hive-wide preference') < content.indexOf('Host-specific preference'));
  await host.getByRole('button', { name: 'Use inherited instructions', exact: true }).click();
  await expect.poll(() => readFile(target, 'utf8'), { timeout: 20000 }).not.toContain('Host-specific preference');
  assert.ok((await readFile(target, 'utf8')).includes('Hive-wide preference'));
  await writeFile(target, 'User edit must survive');
  await expect.poll(async () => await host.textContent(), { timeout: 35000 }).toContain('conflict');
  assert.equal(await readFile(target, 'utf8'), 'User edit must survive');
  const history = await f.client.request('objects.history', { objectId: saved.id, limit: 50 });
  assert.equal(history.items.length, 1);
  });
