/** Hive's publication policy. Service publications belong to their own registries. */
export const coreMcpNames: Record<string, string> = {
  "system.status": "hive_status",
  "system.instructions": "ivy_instructions",
  "system.toolSchema": "ivy_tool_schema",
  "system.inspectStorage": "hive_inspect_storage",
  "system.diagnostics": "hive_diagnostics",
  "objects.stat": "hive_object_read",
  "objects.read": "hive_object_read",
  "objects.write": "hive_object_write",
  "objects.search": "hive_object_search",
  "objects.query": "hive_object_search",
  "objects.list": "hive_object_list",
  "objects.history": "hive_object_read",
  "objects.tree": "hive_object_list",
  "objects.move": "hive_object_move",
  "objects.reorder": "hive_object_move",
  "objects.archive": "hive_object_archive",
  "retention.preview": "hive_retention_status",
  "retention.status": "hive_retention_status",
  "contracts.summaries": "hive_schema_list",
  "contracts.get": "hive_schema_get",
  "contracts.register": "hive_schema_register",
  "contracts.validate": "hive_schema_validate",
  "hosts.list": "hive_hosts",
  "hosts.observations": "hive_hosts",
  "hostConfigurations.list": "hive_host_configuration_list",
  "hostConfigurations.edit": "hive_host_configuration_read",
  "hostConfigurations.save": "hive_host_configuration_update",
  "hostConfigurations.history": "hive_host_configuration_read",
  "serviceNodes.list": "hive_service_nodes",
  "serviceNodes.get": "hive_service_node_get",
  "serviceNodes.contracts": "hive_service_node_get",
  "inventory.list": "hive_resources",
  "inventory.get": "hive_resource_get",
  "topics.list": "hive_event_topics",
  "events.read": "hive_event_read",
  "packages.catalog": "hive_package_catalog",
  "packages.authorizeUpload": "hive_authorize_package_upload",
  "uis.get": "hive_ui_get",
  "uis.catalog": "hive_ui_catalog",
  "uis.releases": "hive_ui_get",
  "uis.inspect": "hive_ui_inspect",
  "uis.deploy": "hive_ui_deploy",
  "uis.rollback": "hive_ui_rollback",
  "deployments.list": "hive_deployment_list",
  "deployments.get": "hive_deployment_get",
  "wiki.search": "wiki_search",
  "wiki.list": "wiki_list",
  "wiki.read": "wiki_read",
  "wiki.create": "wiki_create",
  "wiki.update": "wiki_update",
  "wiki.history": "wiki_read",
  "wiki.move": "wiki_update",
  "wiki.archive": "wiki_update",
};

/** Hive owns its core endpoint policy; registered services own theirs in RegistrySync. */
export const publicCoreMcpMethods = new Set([
  "system.status",
  "system.instructions",
  "system.toolSchema",
  "objects.stat", "objects.read", "objects.write", "objects.search", "objects.query",
  "objects.list", "objects.history", "objects.tree", "objects.move", "objects.reorder", "objects.archive",
  "contracts.summaries", "contracts.get", "contracts.register", "topics.list",
  "wiki.search", "wiki.list", "wiki.read", "wiki.create", "wiki.update", "wiki.history", "wiki.move", "wiki.archive",
]);
