<script setup lang="ts">
import { ref, watch } from 'vue';
import { Alert, AlertDescription, Button, Input, Label, OptionSelect, Textarea } from '@ivy/ui';
import { base, client } from './runtime';
import type { TaskBoard } from './runtime';
const props = defineProps<{ scope: string; disabled: boolean; canFinalize: boolean }>();
const emit = defineEmits<{ save: [kind: 'intermediate' | 'final', content: TaskBoard.ResultContent] }>();
const content = ref<TaskBoard.ResultContent>({ summary: '', artifacts: [], checks: [], codeReferences: [], repositoryResult: null, limitations: [] }), kind = ref<'intermediate' | 'final'>('intermediate');
const objectId = ref(''), revision = ref(''), label = ref(''), error = ref<string | null>(null), busy = ref(false);
const key = 'ivy:task-board:result-draft:' + base.href + props.scope;
try { const saved = JSON.parse(sessionStorage.getItem(key) ?? 'null'); if (saved) { content.value = saved.content; kind.value = saved.kind; } } catch { error.value = 'The saved result draft could not be read.'; }
watch([content, kind], () => { try { sessionStorage.setItem(key, JSON.stringify({ content: content.value, kind: kind.value })); } catch { error.value = 'The result draft cannot be retained in this tab.'; } }, { deep: true });
const addArtifact = async () => {
  if (busy.value) return; busy.value = true; error.value = null;
  try {
    const read = await client.request('objects.read', { objectId: objectId.value.trim(), ...(revision.value ? { revision: Number(revision.value) } : {}) });
    content.value.artifacts.push({ object: { objectId: read.object.id, revision: read.revision.revision }, label: label.value.trim() || read.object.name, contentHash: read.revision.contentHash, mediaType: read.revision.mediaType });
    objectId.value = ''; revision.value = ''; label.value = '';
  } catch (cause) { error.value = cause instanceof Error ? cause.message : 'The artifact could not be pinned.'; }
  finally { busy.value = false; }
};
</script>
<template><form class="space-y-4" @submit.prevent="emit('save', kind, content)"><div class="space-y-2"><Label for="result-kind">Result kind</Label><OptionSelect id="result-kind" v-model="kind" :disabled="disabled"><option value="intermediate">Intermediate material</option><option v-if="canFinalize" value="final">Final manual result for review</option></OptionSelect></div>
  <div class="space-y-2"><Label for="result-summary">Saved result</Label><Textarea id="result-summary" v-model="content.summary" required :maxlength="1048576" :disabled="disabled" class="min-h-40" /></div>
  <section class="space-y-3"><h3 class="font-semibold">Artifacts</h3><p class="text-sm text-muted-foreground">Attach a saved Hive Object. Its exact revision and content hash are retained with the result.</p><div class="grid gap-2 md:grid-cols-3"><div class="space-y-1"><Label for="artifact-id">Object ID</Label><Input id="artifact-id" v-model="objectId" :disabled="disabled" /></div><div class="space-y-1"><Label for="artifact-revision">Revision · blank for current</Label><Input id="artifact-revision" v-model="revision" type="number" min="1" :disabled="disabled" /></div><div class="space-y-1"><Label for="artifact-label">Artifact label</Label><Input id="artifact-label" v-model="label" :disabled="disabled" /></div></div><Button type="button" variant="outline" :disabled="disabled || busy || !objectId.trim() || content.artifacts.length >= 256" @click="addArtifact">Attach saved artifact</Button><div v-for="(artifact, index) in content.artifacts" :key="index" class="flex items-center justify-between gap-3 text-sm"><span class="break-all">{{ artifact.label }} · {{ artifact.object.objectId }} · revision {{ artifact.object.revision }}</span><Button type="button" size="sm" variant="ghost" :disabled="disabled" @click="content.artifacts.splice(index, 1)">Remove artifact</Button></div></section>
  <section class="space-y-3"><h3 class="font-semibold">Checks</h3><div v-for="(check, index) in content.checks" :key="index" class="grid gap-2 rounded-lg border p-3 md:grid-cols-2"><div><Label :for="'check-name-' + index">Check name</Label><Input :id="'check-name-' + index" v-model="check.name" required :disabled="disabled" /></div><div><Label :for="'check-status-' + index">Check status</Label><OptionSelect :id="'check-status-' + index" v-model="check.status" :disabled="disabled"><option v-for="state in ['passed', 'failed', 'not_run', 'blocked']" :key="state">{{ state }}</option></OptionSelect></div><div class="md:col-span-2"><Label :for="'check-detail-' + index">Check evidence and limits</Label><Textarea :id="'check-detail-' + index" v-model="check.detail" :disabled="disabled" /></div><Button type="button" variant="ghost" :disabled="disabled" @click="content.checks.splice(index, 1)">Remove check</Button></div><Button type="button" variant="outline" :disabled="disabled || content.checks.length >= 256" @click="content.checks.push({ name: '', status: 'not_run', detail: '', evidence: [] })">Add check</Button></section>
  <section class="space-y-3"><h3 class="font-semibold">Code and review links</h3><div v-for="(link, index) in content.codeReferences" :key="index" class="grid gap-2 rounded-lg border p-3 md:grid-cols-2"><div><Label :for="'link-label-' + index">Link label</Label><Input :id="'link-label-' + index" v-model="link.label" required :disabled="disabled" /></div><div><Label :for="'link-kind-' + index">Link kind</Label><OptionSelect :id="'link-kind-' + index" v-model="link.kind" :disabled="disabled"><option v-for="value in ['repository', 'commit', 'pull_request', 'issue', 'file']" :key="value">{{ value }}</option></OptionSelect></div><div class="md:col-span-2"><Label :for="'link-url-' + index">HTTP(S) URL</Label><Input :id="'link-url-' + index" v-model="link.url" type="url" pattern="https?://.*" required :disabled="disabled" /></div><Button type="button" variant="ghost" :disabled="disabled" @click="content.codeReferences.splice(index, 1)">Remove link</Button></div><Button type="button" variant="outline" :disabled="disabled || content.codeReferences.length >= 256" @click="content.codeReferences.push({ kind: 'pull_request', url: '', label: '', commit: null })">Add code link</Button></section>
  <div class="space-y-2"><Label for="result-limitations">Limitations · one per line</Label><Textarea id="result-limitations" :model-value="content.limitations.join('\n')" @update:model-value="content.limitations = String($event).split('\n').filter(Boolean)" :disabled="disabled" /></div>
  <Alert v-if="error" variant="destructive"><AlertDescription>{{ error }}</AlertDescription></Alert><Button type="submit" :disabled="disabled || !content.summary.trim() || kind === 'final' && !canFinalize || !!error">Save material result</Button>
</form></template>
